version: '3'
name: frontend2025

services:
  nginx:
    image: nginx:latest
    ports:
      - "5557:5557"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
      - ./dist:/app:ro
